version: '3.2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "20080:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
  php:
    build: ./docker/php/ 
    volumes:
      - ./web:/var/www/html:delegated
    restart: always
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=infuse_media
    restart: always
    ports:
      - "32769:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
